version: "3"
services:
    db:
        image: postgres
        container_name: postgres_sql
        restart: always
        environment:
            - POSTGRES_ROOT_PASSWORD="secret"
    backend:
        image: backend
        build: ./backend
        depends_on:
            - db
        container_name: training/frontend
        restart: always
        ports:
            - "5000:5000"
    frontend:
        image: frontend
        build: ./frontend
        depends_on:
            - backend
        container_name: training/frontend
        restart: always
        ports:
            - "3000:3000"
