version: "3"
services:
    db:
        image: postgres
        container_name: postgres_sql
        restart: always
        environment:
            - POSTGRES_ROOT_PASSWORD="secret"
        volumes:
            - data-volume:/data/db
        networks:
            - app-network
    backend:
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        command: npm start
        volumes:
            - ./backend/:/app/backend
            - /app/backend/node_modules
        environment:
            - NODE_ENV=development
        depends_on:
            - db
        restart: always
        ports:
            - "5000:5000"
        networks:
            - app-network
    frontend:
        image: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        command: npm start
        volumes:
            - ./frontend/:/app/frontend
            - /app/frontend/node_modules
        depends_on:
            - backend
        container_name: frontend
        restart: always
        ports:
            - "3000:3000"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local
