version: "3"
services:
    db:
        image: postgres
        container_name: postgres_sql
        restart: always
        environment:
            - POSTGRES_ROOT_PASSWORD="secret"
    backend:
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: training/backend
        command: npm start
        volumes:
            - ./backend/:/app
            - /app/node_modules
        env_file: ./backend/.env
        environment:
            - NODE_ENV=development
        depends_on:
            - db
        restart: always
        ports:
            - "5000:5000"
    frontend:
        image: frontend
        build: ./frontend
        depends_on:
            - backend
        container_name: training/frontend
        restart: always
        ports:
            - "3000:3000"
