name: GitHub Actions for Training
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Build Frontend Image
              run: |
                  docker build ./frontend -t training/frontend:1.0.0
            - name: Build Backend Image
              run: |
                  docker build ./backend -t training/backend:1.0.0
